# Generated by Django 5.1.3 on 2024-12-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='commects',
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
